run:
  timeout: 5m
linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gosimple
    - ineffassign
    - typecheck
    - goimports
    - misspell
    - unparam
linters-settings:
  goimports:
    local-prefixes: github.com/shinhauhuang/go-fsm
issues:
  exclude-dirs:
    - ent
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
