// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// StateMachinesColumns holds the columns for the "state_machines" table.
	StateMachinesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "machine_id", Type: field.TypeString, Unique: true},
		{Name: "current_state", Type: field.TypeString},
	}
	// StateMachinesTable holds the schema information for the "state_machines" table.
	StateMachinesTable = &schema.Table{
		Name:       "state_machines",
		Columns:    StateMachinesColumns,
		PrimaryKey: []*schema.Column{StateMachinesColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		StateMachinesTable,
	}
)

func init() {
}
