// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/shinhauhuang/go-fsm/ent/predicate"
	"github.com/shinhauhuang/go-fsm/ent/statetransition"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StateTransitionDelete is the builder for deleting a StateTransition entity.
type StateTransitionDelete struct {
	config
	hooks    []Hook
	mutation *StateTransitionMutation
}

// Where appends a list predicates to the StateTransitionDelete builder.
func (std *StateTransitionDelete) Where(ps ...predicate.StateTransition) *StateTransitionDelete {
	std.mutation.Where(ps...)
	return std
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (std *StateTransitionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, std.sqlExec, std.mutation, std.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (std *StateTransitionDelete) ExecX(ctx context.Context) int {
	n, err := std.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (std *StateTransitionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(statetransition.Table, sqlgraph.NewFieldSpec(statetransition.FieldID, field.TypeInt))
	if ps := std.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, std.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	std.mutation.done = true
	return affected, err
}

// StateTransitionDeleteOne is the builder for deleting a single StateTransition entity.
type StateTransitionDeleteOne struct {
	std *StateTransitionDelete
}

// Where appends a list predicates to the StateTransitionDelete builder.
func (stdo *StateTransitionDeleteOne) Where(ps ...predicate.StateTransition) *StateTransitionDeleteOne {
	stdo.std.mutation.Where(ps...)
	return stdo
}

// Exec executes the deletion query.
func (stdo *StateTransitionDeleteOne) Exec(ctx context.Context) error {
	n, err := stdo.std.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{statetransition.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (stdo *StateTransitionDeleteOne) ExecX(ctx context.Context) {
	if err := stdo.Exec(ctx); err != nil {
		panic(err)
	}
}
