// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"github.com/shinhauhuang/go-fsm/ent/predicate"
	"github.com/shinhauhuang/go-fsm/ent/statemachine"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StateMachineDelete is the builder for deleting a StateMachine entity.
type StateMachineDelete struct {
	config
	hooks    []Hook
	mutation *StateMachineMutation
}

// Where appends a list predicates to the StateMachineDelete builder.
func (smd *StateMachineDelete) Where(ps ...predicate.StateMachine) *StateMachineDelete {
	smd.mutation.Where(ps...)
	return smd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (smd *StateMachineDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, smd.sqlExec, smd.mutation, smd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (smd *StateMachineDelete) ExecX(ctx context.Context) int {
	n, err := smd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (smd *StateMachineDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(statemachine.Table, sqlgraph.NewFieldSpec(statemachine.FieldID, field.TypeInt))
	if ps := smd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, smd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	smd.mutation.done = true
	return affected, err
}

// StateMachineDeleteOne is the builder for deleting a single StateMachine entity.
type StateMachineDeleteOne struct {
	smd *StateMachineDelete
}

// Where appends a list predicates to the StateMachineDelete builder.
func (smdo *StateMachineDeleteOne) Where(ps ...predicate.StateMachine) *StateMachineDeleteOne {
	smdo.smd.mutation.Where(ps...)
	return smdo
}

// Exec executes the deletion query.
func (smdo *StateMachineDeleteOne) Exec(ctx context.Context) error {
	n, err := smdo.smd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{statemachine.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (smdo *StateMachineDeleteOne) ExecX(ctx context.Context) {
	if err := smdo.Exec(ctx); err != nil {
		panic(err)
	}
}
