// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"go-fsm/ent/predicate"
	"go-fsm/ent/statemachine"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// StateMachineQuery is the builder for querying StateMachine entities.
type StateMachineQuery struct {
	config
	ctx        *QueryContext
	order      []statemachine.OrderOption
	inters     []Interceptor
	predicates []predicate.StateMachine
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the StateMachineQuery builder.
func (smq *StateMachineQuery) Where(ps ...predicate.StateMachine) *StateMachineQuery {
	smq.predicates = append(smq.predicates, ps...)
	return smq
}

// Limit the number of records to be returned by this query.
func (smq *StateMachineQuery) Limit(limit int) *StateMachineQuery {
	smq.ctx.Limit = &limit
	return smq
}

// Offset to start from.
func (smq *StateMachineQuery) Offset(offset int) *StateMachineQuery {
	smq.ctx.Offset = &offset
	return smq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (smq *StateMachineQuery) Unique(unique bool) *StateMachineQuery {
	smq.ctx.Unique = &unique
	return smq
}

// Order specifies how the records should be ordered.
func (smq *StateMachineQuery) Order(o ...statemachine.OrderOption) *StateMachineQuery {
	smq.order = append(smq.order, o...)
	return smq
}

// First returns the first StateMachine entity from the query.
// Returns a *NotFoundError when no StateMachine was found.
func (smq *StateMachineQuery) First(ctx context.Context) (*StateMachine, error) {
	nodes, err := smq.Limit(1).All(setContextOp(ctx, smq.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{statemachine.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (smq *StateMachineQuery) FirstX(ctx context.Context) *StateMachine {
	node, err := smq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first StateMachine ID from the query.
// Returns a *NotFoundError when no StateMachine ID was found.
func (smq *StateMachineQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = smq.Limit(1).IDs(setContextOp(ctx, smq.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{statemachine.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (smq *StateMachineQuery) FirstIDX(ctx context.Context) int {
	id, err := smq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single StateMachine entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one StateMachine entity is found.
// Returns a *NotFoundError when no StateMachine entities are found.
func (smq *StateMachineQuery) Only(ctx context.Context) (*StateMachine, error) {
	nodes, err := smq.Limit(2).All(setContextOp(ctx, smq.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{statemachine.Label}
	default:
		return nil, &NotSingularError{statemachine.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (smq *StateMachineQuery) OnlyX(ctx context.Context) *StateMachine {
	node, err := smq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only StateMachine ID in the query.
// Returns a *NotSingularError when more than one StateMachine ID is found.
// Returns a *NotFoundError when no entities are found.
func (smq *StateMachineQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = smq.Limit(2).IDs(setContextOp(ctx, smq.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{statemachine.Label}
	default:
		err = &NotSingularError{statemachine.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (smq *StateMachineQuery) OnlyIDX(ctx context.Context) int {
	id, err := smq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of StateMachines.
func (smq *StateMachineQuery) All(ctx context.Context) ([]*StateMachine, error) {
	ctx = setContextOp(ctx, smq.ctx, ent.OpQueryAll)
	if err := smq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*StateMachine, *StateMachineQuery]()
	return withInterceptors[[]*StateMachine](ctx, smq, qr, smq.inters)
}

// AllX is like All, but panics if an error occurs.
func (smq *StateMachineQuery) AllX(ctx context.Context) []*StateMachine {
	nodes, err := smq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of StateMachine IDs.
func (smq *StateMachineQuery) IDs(ctx context.Context) (ids []int, err error) {
	if smq.ctx.Unique == nil && smq.path != nil {
		smq.Unique(true)
	}
	ctx = setContextOp(ctx, smq.ctx, ent.OpQueryIDs)
	if err = smq.Select(statemachine.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (smq *StateMachineQuery) IDsX(ctx context.Context) []int {
	ids, err := smq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (smq *StateMachineQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, smq.ctx, ent.OpQueryCount)
	if err := smq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, smq, querierCount[*StateMachineQuery](), smq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (smq *StateMachineQuery) CountX(ctx context.Context) int {
	count, err := smq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (smq *StateMachineQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, smq.ctx, ent.OpQueryExist)
	switch _, err := smq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (smq *StateMachineQuery) ExistX(ctx context.Context) bool {
	exist, err := smq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the StateMachineQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (smq *StateMachineQuery) Clone() *StateMachineQuery {
	if smq == nil {
		return nil
	}
	return &StateMachineQuery{
		config:     smq.config,
		ctx:        smq.ctx.Clone(),
		order:      append([]statemachine.OrderOption{}, smq.order...),
		inters:     append([]Interceptor{}, smq.inters...),
		predicates: append([]predicate.StateMachine{}, smq.predicates...),
		// clone intermediate query.
		sql:  smq.sql.Clone(),
		path: smq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MachineID string `json:"machine_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.StateMachine.Query().
//		GroupBy(statemachine.FieldMachineID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (smq *StateMachineQuery) GroupBy(field string, fields ...string) *StateMachineGroupBy {
	smq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &StateMachineGroupBy{build: smq}
	grbuild.flds = &smq.ctx.Fields
	grbuild.label = statemachine.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MachineID string `json:"machine_id,omitempty"`
//	}
//
//	client.StateMachine.Query().
//		Select(statemachine.FieldMachineID).
//		Scan(ctx, &v)
func (smq *StateMachineQuery) Select(fields ...string) *StateMachineSelect {
	smq.ctx.Fields = append(smq.ctx.Fields, fields...)
	sbuild := &StateMachineSelect{StateMachineQuery: smq}
	sbuild.label = statemachine.Label
	sbuild.flds, sbuild.scan = &smq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a StateMachineSelect configured with the given aggregations.
func (smq *StateMachineQuery) Aggregate(fns ...AggregateFunc) *StateMachineSelect {
	return smq.Select().Aggregate(fns...)
}

func (smq *StateMachineQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range smq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, smq); err != nil {
				return err
			}
		}
	}
	for _, f := range smq.ctx.Fields {
		if !statemachine.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if smq.path != nil {
		prev, err := smq.path(ctx)
		if err != nil {
			return err
		}
		smq.sql = prev
	}
	return nil
}

func (smq *StateMachineQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*StateMachine, error) {
	var (
		nodes = []*StateMachine{}
		_spec = smq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*StateMachine).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &StateMachine{config: smq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, smq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (smq *StateMachineQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := smq.querySpec()
	_spec.Node.Columns = smq.ctx.Fields
	if len(smq.ctx.Fields) > 0 {
		_spec.Unique = smq.ctx.Unique != nil && *smq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, smq.driver, _spec)
}

func (smq *StateMachineQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(statemachine.Table, statemachine.Columns, sqlgraph.NewFieldSpec(statemachine.FieldID, field.TypeInt))
	_spec.From = smq.sql
	if unique := smq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if smq.path != nil {
		_spec.Unique = true
	}
	if fields := smq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, statemachine.FieldID)
		for i := range fields {
			if fields[i] != statemachine.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := smq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := smq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := smq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := smq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (smq *StateMachineQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(smq.driver.Dialect())
	t1 := builder.Table(statemachine.Table)
	columns := smq.ctx.Fields
	if len(columns) == 0 {
		columns = statemachine.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if smq.sql != nil {
		selector = smq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if smq.ctx.Unique != nil && *smq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range smq.predicates {
		p(selector)
	}
	for _, p := range smq.order {
		p(selector)
	}
	if offset := smq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := smq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// StateMachineGroupBy is the group-by builder for StateMachine entities.
type StateMachineGroupBy struct {
	selector
	build *StateMachineQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (smgb *StateMachineGroupBy) Aggregate(fns ...AggregateFunc) *StateMachineGroupBy {
	smgb.fns = append(smgb.fns, fns...)
	return smgb
}

// Scan applies the selector query and scans the result into the given value.
func (smgb *StateMachineGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, smgb.build.ctx, ent.OpQueryGroupBy)
	if err := smgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StateMachineQuery, *StateMachineGroupBy](ctx, smgb.build, smgb, smgb.build.inters, v)
}

func (smgb *StateMachineGroupBy) sqlScan(ctx context.Context, root *StateMachineQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(smgb.fns))
	for _, fn := range smgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*smgb.flds)+len(smgb.fns))
		for _, f := range *smgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*smgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := smgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// StateMachineSelect is the builder for selecting fields of StateMachine entities.
type StateMachineSelect struct {
	*StateMachineQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sms *StateMachineSelect) Aggregate(fns ...AggregateFunc) *StateMachineSelect {
	sms.fns = append(sms.fns, fns...)
	return sms
}

// Scan applies the selector query and scans the result into the given value.
func (sms *StateMachineSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sms.ctx, ent.OpQuerySelect)
	if err := sms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*StateMachineQuery, *StateMachineSelect](ctx, sms.StateMachineQuery, sms, sms.inters, v)
}

func (sms *StateMachineSelect) sqlScan(ctx context.Context, root *StateMachineQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sms.fns))
	for _, fn := range sms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
