// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// StateMachine is the predicate function for statemachine builders.
type StateMachine func(*sql.Selector)

// StateTransition is the predicate function for statetransition builders.
type StateTransition func(*sql.Selector)
